### ISSUE TITLE
Require wise2c/kubeadm-version docker image for arm64

### ISSUE THREAD

**Issue by odidev** [wise2c-devops/kubeadm-version#1]
Hi Team,

I am working on adding ARM64 support in Travis-CI for **wise2c-devops/breeze** package, but I was facing an issue in pulling **wise2c/kubeadm-version** image for arm64 as it is not available in the docker hub.

I have successfully built the image for arm64 after doing the below changes.

Commit Link - https://github.com/odidev/kubeadm-version/commit/0a4310ef6dc03a5c5f61598dc2987503e213ad3e
 
If you are interested, I can raise a PR for the changes required to build an arm64 image. It will be very helpful if this image is available for the arm64 platform.

**Comment by alanpeng** [comment]
Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. However, we have no more free credits on travis.com. We are transferring all projects to gitlab-ci now.

**Comment by alanpeng** [comment]
We are considering supporting ARM64 infrastructure for project Breeze. For the purpose of this, we will update some gitlab-ci scripts.
